### ISSUE TITLE
Won't go into Test Mode

### ISSUE THREAD

**Issue by thatdebianguy** [VNNGYN/Windows-RT-8.1-Development-Tool#9]
Hi,
The work you are doing is invaluable. I feel so bad for my poor surface 2 rt sitting there gathering dust because of Microsoft. This thing would be bliss on linux. I have tried the solutions down at the bottom of the guide and the infected updates are definitely all gone. I don't know why it won't boot into test signing mode - it just boots into the regular desktop. Do I need to disable bitlocker?

Thanks

**Comment by Qiangong2** [comment]
Sometimes, even though it is shown as the updates are removed, they really aren't. You may have to run the tool many times to be able to get it working

**Comment by VNNGYN** [comment]
The Development Tool will be updated soon. Sorry for the delay!

**Comment by thatdebianguy** [comment]
Windows Update is not stuck so I don't want to have to put up with doing a factory reset
How far have people got with porting Chromium or Firefox to the RT OS? I am aware that THUMB-2 is an issue but could it not be possible to reverse engineer ie 10 to make use of the activex and thumb2 driver or even get our own custom drivers for the nvidia chip? Can we install our own unsigned drivers or can we just make them work by signing them

**Comment by thatdebianguy** [comment]
One more question, can we actually unlock secure boot on windows rt 8.1? What roadblocks are we facing that is not allowing us to boot a linux kernel on a Surface 2 RT

**Comment by thatdebianguy** [comment]
I have tried running the tool again and again and it will not go into test signing mode please help

**Comment by thatdebianguy** [comment]
Sorry to be rude but I'm desperate. I need to liberate this device!

**Comment by VNNGYN** [comment]
I just tested and released a new version the Development Tool. About your other questions, I would be happy to answer them, but I dropped the development on Windows RT 8.1 a while ago (except for the Development Tool). You may visit the XDA forums and post your questions there. I hope they will be able to answer them for you.

**Comment by OMGkenny00** [comment]
hello, first let me thank you for your hard work in developing this tool, it will offer people a lot more options on Windows RT, since Microsoft won't bother fixing their mistakes.

I'm trying to use the tool but I am facing the same problem, the steps I made to try and getting it to work:
 -Did the standard install of the tool and instructions. (failed to boot)
 -Did a number of tries uninstalling Infected updates. (failed to boot)
Notes: I tried the manual uninstall also using the infected list, I did not seem to find the updates installed, I used the KB value as a guide since the update names of the list and mine don't match. Image attached. If there is an alternative way to uninstalling them please let me know. Also, when I tried to uninstall the updates using the tool, when the second window of prompts appears to uninstall I notice that one of the updates prints a different message, although I am not able to see it or take a screenshot because its so fast. is there anyway to print a log?
 -Tried blocking Windows Update using the tool multiple times. (failed to boot)
Notes: It does not seem to be active because in task manager > services its stopped but I noticed that when I access service manager it was set to Manual (Trigger Start), I tried setting it to disabled and repeating the standard tool process again but with the same result.
 -Tried to boot to test mode multiple times. (failed to boot)

The only thing I still did not try was the factory reset since for now I can't access my recovery external drive. winch I'm still trying to avoid.

I will help in solving the issue in any way I can. just tell me what is needed.
Side question: I noticed there is a addon for developing purposes does that mean that if I can get into test mode and install the add on, I can recompile other apps directly from surface?

**Comment by OMGkenny00** [comment]
Edit: Image since github does not support internet explorer anymore. https://ibb.co/j8cnZW1
I'm on Windows Surface RT 1st gen. Running Wndows 8.1 with all the updates.

**Comment by thatdebianguy** [comment]
Hi @OMGkenny00,
I found that you have to run the infected updates script until it either doesn't configure windows upon reboot or the disk space increase. Run it at least three times when you see that it doesn't configure windows AND disk space does not increase then you should try. I am currently removing the infected updates in the new 1118 build and every time I run the script it is uninstalling things.

So continuously run the script until disk space does not increase then try. Not sure if you are doing this already. As Qianqong said it shows updates are gone but really they're not and they are still poisoning the test mode.
AFAIK you cannot get a compiler to run on the surface, but if you have any windows computer you can compile apps by getting the missings dlls from the surface, feed them into visual studio 2012. The entire step by step process is on xda - I don't exactly remember the details of how to do it (since I haven't actually done it myself yet).
Also afaik you only block windows update to stop it reinstalling old updates correct me if I'm wrong.

**Comment by thatdebianguy** [comment]
Hey @VNNGYN 
THANKS you new tool worked. I am now in test mode.

Time to breathe some life into this poor device.
